services:
  app:
    build: .
    restart: unless-stopped
    container_name: fastapi_poc_backend
    volumes:
      - ./alembic:/alembic
    ports:
      - "9000"
    depends_on:
      - db
    labels:
      - traefik.enable=true
      - traefik.http.routers.fastapi.rule=Host(`fastapi.localhost`)
      - traefik.http.routers.fastapi-secure.rule=Host(`fastapi.localhost`)
      - traefik.http.routers.fastapi-secure.entrypoints=websecure
      - traefik.http.routers.fastapi-secure.tls=true
      - traefik.http.routers.fastapi-secure.tls.certresolver=myresolver

  db:
    container_name: fastapi_poc_db
    image: postgres:12
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    env_file:
      - ./.env

  traefik:
    container_name: fastapi_poc_traefik
    image: traefik:v2.3
    ports:
      - "80:80"
      - "8080:8080"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik.toml:/etc/traefik/traefik.toml

volumes:  
  db_data: {}
